### PR TITLE
Add basic inputfield for manual verification

### PR DESCRIPTION
**Pull request by Ishadijcks**
image

### CODE REVIEW

**Comment by MatthijsKok** [comment]
How would you respond to a challenge without knowing the IBAN to respond to? A Challenge string in itself is rather useless without IBAN or the counterparty's verifying key.

**Comment by Ishadijcks** [comment]
Ah I thought that the challenge contained the senders IBAN, adding another input field should fix this.

**Comment by Ishadijcks** [comment]
image

Like this

**Comment by MatthijsKok** [comment]
This would not verify the incoming challenge, only respond to it.
To verify a challenge we will need their public key.

**Review by MatthijsKok — APPROVED** [review]
LGTM

**Pull request merged**
