### PR TITLE
Add environment from resource

### PR DESCRIPTION
**Pull request by joskuijpers**
This PR adds a resource file to the app that contains the environment, so it does not need to be in the code. This file is not in the github repository so the API key can stay secret.

Add this to your local repo at `BankChain/app/src/main/res/raw/environment.xml`:
```xml
<?xml version="1.0" encoding="utf-8"?>
<environment>
    <value name="bank">Bunq</value>
    <value name="bankUrl"></value>
    <value name="bankApiKey"></value>
</environment>
```

And fill in the blanks. This file is ignored and thus is not accidentally uploaded to git.

At the moment this does not work gracefully: if you do not add this file, build will fail. Although maybe that is something we should want.

### CODE REVIEW

**Comment by Ishadijcks** [comment]
+1 if you have added this file.

**Comment by joskuijpers** [comment]
Can't :( if it is comitted it is not ignored anymore. I tried that. So that would defeat its purpose

**Comment by MatthijsKok** [comment]
This seems insanely overkill. We should probably put this in the config folder as a keys.conf.example, after which you could copy to keys.conf your own keys.

**Review by MatthijsKok — CHANGES_REQUESTED** [review]
Therefore i dissapprove for now

**Comment by joskuijpers** [comment]
What is 'keys.conf'? What is in there, how do you load it?

**Comment by joskuijpers** [comment]
And also, how can you then use a different environment when testing?

I have no clue.

**Comment by MatthijsKok** [comment]
I was just giving an example to how you _could_ do this. I just know that this must be done simpler

**Comment by joskuijpers** [comment]
You are suggesting another way, i don't know another, testable, way.

I could add an empty environment.xml.example in the folder.

**Comment by MatthijsKok** [comment]
please do

**Comment by joskuijpers** [comment]
@MatthijsKok Added

**Comment by joskuijpers** [comment]
@MatthijsKok can you re-review this? I really want to merge it for everyone else.

**Comment by joskuijpers** [comment]
Moet ook rebasen maar weet even niet hoe.

**Review by MatthijsKok — APPROVED** [review]
Changes added

**Pull request merged**
