### PR TITLE
Feature/blockchain

### PR DESCRIPTION
**Pull request by RvdK**
adds blockchain and buisness logic

### CODE REVIEW

**Comment by joskuijpers** [comment]
I reviewed this already with you, live, with many changes (see the commits).

GUI tests need fixing. And some new tests are needed. Other than that, good.

**Comment by RvdK** [comment]
Better code has some issues with our new classes because of coupling however we are of the opinion that decreasing the coupling would create complexity therefore defeating its original purpose

**Comment by MatthijsKok** [comment]
"decreasing the coupling would create complexity" by requiring abstract factories, interfaces with only one implementation and more.

**Review by joskuijpers — APPROVED** [review]
Great! We worked on this together, reviewed all of it. Approve!

**Pull request merged**
